#ifndef __MMC_CONFIG_SETTING
#define __MMC_CONFIG_SETTING

#define MMC_CONFIG_SETTING_SLEEP 1
#define MMC_CONFIG_SETTING_BKOPS 1
#define MMC_CONFIG_SETTING_HPI 1
#define MMC_CONFIG_SETTING_RPMB 1
#define MMC_CONFIG_SETTING_ENHANCED_AREA 1
#define MMC_CONFIG_SETTING_DISCARD 1
#define MMC_CONFIG_SETTING_TRIM 1
#define MMC_CONFIG_SETTING_SANITIZE 0
#define MMC_CONFIG_SETTING_PON 1
#define MMC_CONFIG_SETTING_PACKED 1
#define MMC_CONFIG_SETTING_CACHE 1
#define MMC_CONFIG_SETTING_HS200 1

#endif
