ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/eeprom/

obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
obj-$(CONFIG_MSMB_CAMERA) += asus_ois.o
obj-$(CONFIG_MSMB_CAMERA) += onsemi_interface.o
obj-$(CONFIG_MSMB_CAMERA) += onsemi_i2c.o
obj-$(CONFIG_MSMB_CAMERA) += utils.o
