#drivers/input/touchscreen/focaltech_touch
#
#Makefile for flash module
#
ccflags-y += -I$(srctree)/drivers/input/touchscreen/$(CONFIG_TOUCHSCREEN_FTS_DIRECTORY)

	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_ic_table.o
